//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PlanShare.App.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ResourceTexts {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourceTexts() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PlanShare.App.Resources.ResourceTexts", typeof(ResourceTexts).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change password.
        /// </summary>
        public static string CHANGE_PASSWORD {
            get {
                return ResourceManager.GetString("CHANGE_PASSWORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete my account.
        /// </summary>
        public static string DELETE_ACCOUNT {
            get {
                return ResourceManager.GetString("DELETE_ACCOUNT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete profile picture.
        /// </summary>
        public static string DELETE_PROFILE_PICTURE {
            get {
                return ResourceManager.GetString("DELETE_PROFILE_PICTURE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The following errors were found.
        /// </summary>
        public static string FOLLOWING_ERRORS_WERE_FOUND {
            get {
                return ResourceManager.GetString("FOLLOWING_ERRORS_WERE_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login with Email and Password.
        /// </summary>
        public static string LOGIN_WITH_EMAIL_PASSWORD {
            get {
                return ResourceManager.GetString("LOGIN_WITH_EMAIL_PASSWORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your password has been successfully changed..
        /// </summary>
        public static string PASSWORD_SUCCESSFULLY_CHANGED {
            get {
                return ResourceManager.GetString("PASSWORD_SUCCESSFULLY_CHANGED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Already have an account?.
        /// </summary>
        public static string PHRASE_ALREADY_HAS_ACCOUNT {
            get {
                return ResourceManager.GetString("PHRASE_ALREADY_HAS_ACCOUNT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continue with Google.
        /// </summary>
        public static string PHRASE_CONTINUE_WITH_GOOGLE {
            get {
                return ResourceManager.GetString("PHRASE_CONTINUE_WITH_GOOGLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log in!.
        /// </summary>
        public static string PHRASE_DO_LOGIN {
            get {
                return ResourceManager.GetString("PHRASE_DO_LOGIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Don&apos;t have an account?.
        /// </summary>
        public static string PHRASE_DONT_HAVE_ACCOUNT {
            get {
                return ResourceManager.GetString("PHRASE_DONT_HAVE_ACCOUNT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forgot your password?.
        /// </summary>
        public static string PHRASE_FORGOT_YOUR_PASSWORD {
            get {
                return ResourceManager.GetString("PHRASE_FORGOT_YOUR_PASSWORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string PHRASE_LOGIN {
            get {
                return ResourceManager.GetString("PHRASE_LOGIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimum 6 characters.
        /// </summary>
        public static string PHRASE_PASSWORD_REQUIREMENTS {
            get {
                return ResourceManager.GetString("PHRASE_PASSWORD_REQUIREMENTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create your account!.
        /// </summary>
        public static string PHRASE_REGISTER_YOUR_ACCOUNT {
            get {
                return ResourceManager.GetString("PHRASE_REGISTER_YOUR_ACCOUNT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Small tasks, big results.
        /// </summary>
        public static string PHRASE_SMALL_TASKS_BIG_RESULTS {
            get {
                return ResourceManager.GetString("PHRASE_SMALL_TASKS_BIG_RESULTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your profile information has been successfully updated..
        /// </summary>
        public static string PROFILE_INFORMATION_SUCCESSFULLY_UPDATED {
            get {
                return ResourceManager.GetString("PROFILE_INFORMATION_SUCCESSFULLY_UPDATED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your profile photo has been successfully updated..
        /// </summary>
        public static string PROFILE_PHOTO_SUCCESSFULLY_UPDATED {
            get {
                return ResourceManager.GetString("PROFILE_PHOTO_SUCCESSFULLY_UPDATED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while communicating with the server. Please try again later..
        /// </summary>
        public static string SERVER_COMMUNICATION_ERROR {
            get {
                return ResourceManager.GetString("SERVER_COMMUNICATION_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Control your routine with ease - because you deserve more time for what you love!.
        /// </summary>
        public static string SUBTITLE_REGISTER_ACCOUNT {
            get {
                return ResourceManager.GetString("SUBTITLE_REGISTER_ACCOUNT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Take a photo and upload it.
        /// </summary>
        public static string TAKE_PHOTO_UPLOAD {
            get {
                return ResourceManager.GetString("TAKE_PHOTO_UPLOAD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string TITLE_CANCEL {
            get {
                return ResourceManager.GetString("TITLE_CANCEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string TITLE_CLOSE {
            get {
                return ResourceManager.GetString("TITLE_CLOSE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current password.
        /// </summary>
        public static string TITLE_CURRENT_PASSWORD {
            get {
                return ResourceManager.GetString("TITLE_CURRENT_PASSWORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string TITLE_EMAIL {
            get {
                return ResourceManager.GetString("TITLE_EMAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string TITLE_NAME {
            get {
                return ResourceManager.GetString("TITLE_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New password.
        /// </summary>
        public static string TITLE_NEW_PASSWORD {
            get {
                return ResourceManager.GetString("TITLE_NEW_PASSWORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string TITLE_PASSWORD {
            get {
                return ResourceManager.GetString("TITLE_PASSWORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create my account.
        /// </summary>
        public static string TITLE_REGISTER_MY_ACCOUNT {
            get {
                return ResourceManager.GetString("TITLE_REGISTER_MY_ACCOUNT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome.
        /// </summary>
        public static string TITLE_WELCOME {
            get {
                return ResourceManager.GetString("TITLE_WELCOME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Try it again.
        /// </summary>
        public static string TRY_IT_AGAIN {
            get {
                return ResourceManager.GetString("TRY_IT_AGAIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update profile.
        /// </summary>
        public static string UPDATE_PROFILE {
            get {
                return ResourceManager.GetString("UPDATE_PROFILE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload a photo.
        /// </summary>
        public static string UPLOAD_PHOTO {
            get {
                return ResourceManager.GetString("UPLOAD_PHOTO", resourceCulture);
            }
        }
    }
}
